### ISSUE TITLE
Considerar licencia para el código

### ISSUE THREAD

**Issue by jmejia8** [ro-smtz/ars_mathematica.io#1]
Sería buena idea que consideres agregar una licencia para tu código.

**Comment by ro-smtz** [comment]
¡Hola!

La verdad es que soy muy nuevo en esto. ¿Crees que me puedas dar como una ayudadita? Podríamos tener una reunión por Zoom, si gustas.

**Comment by ro-smtz** [comment]
Listo. Ya agregué una Licencia GPL.
